
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cpcompu
 */
public class consultarUsuarios extends javax.swing.JFrame {

   Connection con = null;
   Statement stmt = null;
   String titulos[] = {"Nombre","CI","Edad","Genero","Ocupacion","Direccion","Telefono","Email"};
   String fila[] = new String [8];
   DefaultTableModel modelo;

    public consultarUsuarios() {
        initComponents();
        this.setTitle("Consultar Usuarios");
        this.setLocation(540, 250);
        this.setResizable(false);
        
                try {
            
            String url = "jdbc:mysql://localhost:3306/bdconferecia";
            String usuario = "root";
            String contraseña = "guimer77913525"; 
            
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,usuario,contraseña);
               if (con!= null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               
               stmt = con.createStatement();
               ResultSet rs = stmt.executeQuery("select* from participante");
               
               modelo = new DefaultTableModel(null,titulos);
            
               while(rs.next()) {
                   
                   
                   fila[0] = rs.getString("nombrePar");
                   fila[1] = rs.getString("ciPar");
                   fila[2] = rs.getString("edadPar");
                   fila[3] = rs.getString("generoPar");
                   fila[4] = rs.getString("ocupacionPar");
                   fila[5] = rs.getString("direccionPar");
                   fila[6] = rs.getString("telefonoPar");
                   fila[7] = rs.getString("Email");
                   
                   modelo.addRow(fila);     
               }
               TablaParticipante.setModel(modelo);
               
               
                TableColumn cn = TablaParticipante.getColumn("Nombre");
                cn.setMaxWidth(150);
                TableColumn cc = TablaParticipante.getColumn("CI");
                cc.setMaxWidth(80);
                TableColumn ce = TablaParticipante.getColumn("Edad");
                ce.setMaxWidth(50);
                TableColumn cg = TablaParticipante.getColumn("Genero");
                cg.setMaxWidth(70);
                TableColumn co = TablaParticipante.getColumn("Ocupacion");
                co.setMaxWidth(70);
                TableColumn cd = TablaParticipante.getColumn("Direccion");
                cd.setMaxWidth(150);
                TableColumn ct = TablaParticipante.getColumn("Telefono");
                ct.setMaxWidth(80);
                TableColumn cem = TablaParticipante.getColumn("Email");
                cem.setMaxWidth(150);
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"Error al extraer los datos de la tabla");
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaParticipante = new javax.swing.JTable();
        TituloTabla = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        FondoConsulta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 500));

        TablaParticipante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaParticipante.setAlignmentX(0.0F);
        TablaParticipante.setAlignmentY(0.0F);
        TablaParticipante.setPreferredSize(new java.awt.Dimension(750, 366));
        jScrollPane1.setViewportView(TablaParticipante);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 750, 400));

        TituloTabla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TituloTabla.setText("Lista de Participantes Inscritos:");
        getContentPane().add(TituloTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        botonRegresar.setText("Regresar a Registro");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, -1, -1));
        getContentPane().add(FondoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        this.dispose();
        participantes p = new participantes();
        p.setLocationRelativeTo(null);
        p.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoConsulta;
    private javax.swing.JTable TablaParticipante;
    private javax.swing.JLabel TituloTabla;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
